name = "sienna-tracker"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "sienna-tracker"
database_id = "936f251b-8b30-4422-b9bd-d88167d0fd98"
